---
title: "escuelas"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#install.packages("DataExplorer")
#install.packages("skimr")
#install.packages("readr")
#install.packages("tidyverse")
#install.packages("readxl")
#install.packages("haven")
#install.packages("treemap")
#install.packages("patchwork")
```


```{r}
library(DataExplorer)
library(skimr)
library(haven)
library( dplyr )
library( knitr )
library(readxl)
library(treemap)
library(gridExtra)
library(scales)
library(tidyverse)
library(patchwork)
library(R2OpenBUGS)
```


```{r}
data <- haven::read_dta("./Data/2022-04-25-BD-Prepa-UACh.dta")
``` 


```{r}
colnames(data) <-
c("ciclo",
"aÑo",
"estado",
"MUNICIPIO",
"CURP",
"Sexo",
"vigencia_clv",
"matricula",
"BIOL_I",
"BIOL_II",
"FIS_I",
"FIS_II",
"LOGICA",
"TOP",
"AGR_I",
"DH_I",
"GEO",
"ICE",
"TEOYE_I",
"HIST_I",
"DH_II",
"TEOYE_II",
"COMPUTO",
"AGR_II",
"QUIM_I",
"HIST_II",
"INT_FIL",
"LIT_I",
"AGR_III",
"QUIM_II",
"PSEM",
"ETICA",
"LIT_II",
"AGR_IV",
"SPYC",
"GEN",
"MET",
"SPF",
"SPA",
"FIS_III",
"QUIM_III",
"BIOL_VEG",
"BIOL_AN",
"PRSC",
"FIL_C",
"ALG_I",
"ALG_II",
"G_Y_T",
"CALC_D",
"CALC_I",
"G_AN",
"ING_I",
"ING_II",
"ING_III",
"ING_IV",
"1-publica-privada",
"2-publica-privada-sec",
"SOC3",
"SOC4",
"5-inscripcion",
"6-grado-baja",
"7-motivo-baja",
"8-lengua-indigena",
"9-lengua",
"10-trabajo-actual",
"11-padres-vivos",
"12-jefe",
"13-jefe-indigena",
"14-grupo-jefe",
"15-maximo-estudio",
"16-sector",
"17-empleo-jefe",
"18-jefe-tipo",
"19-gobierno-particular",
"20-antigüedad-eco",
"21-actividad-jefe",
"22-lugar-tierra",
"23-hectareas",
"24-maquinaria",
"25-ascenso",
"26-pareja-universidad",
"27-maximo-pareja",
"28-actividad-pareja",
"29-antigüedad-puesto",
"30-ascenso-pareja",
"31-ascenso",
"32-personas-dependientes",
"33-hermanos-universidad",
"34-serv-medico",
"35-servicio-médico",
"36-propiedad-vivienda",
"37-vivienda",
"38-adquisicion-vivienda",
"39-vivienda-compartida",
"40-energia-elec",
"41-manera",
"42-agua",
"43-drenaje",
"44-piso-tierra",
"45-pisos",
"46-techo-material",
"47-cuartos",
"48-telefono-fijo",
"49-telefono",
"50-cuantos-celular",
"51-tele",
"52-internet",
"53-coche",
"54-marca-coche",
"55-domicilio",
"56-pueblo-comunidad",
"57-lenguas",
"SOC58",
"p61",
"p63",
"pp64")
```


```{r}
cve_calif <- read_excel("./Data/2022-05-07-CLAVES-CALIFICACIONES.xlsx")
```

```{r}
lista_mat<- list()
```

```{r}
lista_mat[[1]] <- list(filter(cve_calif, AÑO == 1, SEM == 1) %>% .$`NOMBRE EN BD`)
lista_mat[[2]] <- list(filter(cve_calif, AÑO == 1, SEM == 2) %>% .$`NOMBRE EN BD`)
lista_mat[[3]] <- list(filter(cve_calif, AÑO == 2, SEM == 1) %>% .$`NOMBRE EN BD`)
lista_mat[[4]] <- list(filter(cve_calif, AÑO == 2, SEM == 2) %>% .$`NOMBRE EN BD`)
lista_mat[[5]] <- list(filter(cve_calif, AÑO == 3, SEM == 1) %>% .$`NOMBRE EN BD`)
lista_mat[[6]] <- list(filter(cve_calif, AÑO == 3, SEM == 2) %>% .$`NOMBRE EN BD`)
```

```{r}
sum <- data.frame(matrix(ncol = 6, nrow = nrow(data)))
column_names <- c("sem_1", "sem_2", "sem_3", "sem_4", "sem_5", "sem_6" )
colnames(sum) <- column_names
```

```{r}
for (i in 1:6) {
  for (j in lista_mat[[i]]){
    sum[i] <- (rowSums(data[,j],na.rm = TRUE)/length(j))
  }
}
```

```{r}
data <- data %>% 
  mutate( sum )
```

```{r}
calif_sem <- sum 
```


```{r}
calif_sem <- calif_sem %>% 
  mutate( estado = data$estado, sexo = data$Sexo, vigencia_clv = data$vigencia_clv, ingreso = data$`31-ascenso`, niv_estudio = data$`15-maximo-estudio` )
```


```{r}
create_report(calif_sem)
```


```{r}
cal_sem_1 <- calif_sem %>% 
  group_by( estado ) %>%  
  summarise(avg_calif=mean(sem_1)) %>%  
  arrange( desc(avg_calif) )  
```

```{r}
cal_sem_1 %>% 
 kable( caption = "Promedio por semestre 1" )
```

```{r}
cal_sem_2 <- calif_sem %>% 
  group_by( estado ) %>%  
  summarise(avg_calif=mean(sem_2)) %>%  
  arrange( desc(avg_calif) ) 
```


```{r}
cal_sem_2 %>% 
 kable( caption = "Promedio por semestre 2" )
```



```{r}
cal_sem_3 <- calif_sem %>% 
  group_by( estado ) %>%  
  summarise(avg_calif=mean(sem_3)) %>%  
  arrange( desc(avg_calif) ) 
```

```{r}
cal_sem_4 <- calif_sem %>% 
  group_by( estado ) %>%  
  summarise(avg_calif=mean(sem_4)) %>%  
  arrange( desc(avg_calif) ) 
```

```{r}
cal_sem_5 <- calif_sem %>% 
  group_by( estado ) %>%  
  summarise(avg_calif=mean(sem_5)) %>%  
  arrange( desc(avg_calif) ) 
```

```{r}
cal_sem_6 <- calif_sem %>% 
  group_by( estado ) %>%  
  summarise(avg_calif=mean(sem_6)) %>%  
  arrange( desc(avg_calif) ) 
```

```{r}
binwidth_min <- 6
g_1 <- ggplot(calif_sem, aes(x = sem_1, )) + geom_histogram(binwidth = binwidth_min, col = 'blue')
g_2 <- ggplot(calif_sem, aes(x = sem_2)) + geom_histogram(binwidth = binwidth_min, col = 'red')
g_3 <- ggplot(calif_sem, aes(x = sem_3)) + geom_histogram(binwidth = binwidth_min, col = 'green')
g_4 <- ggplot(calif_sem, aes(x = sem_4)) + geom_histogram(binwidth = binwidth_min, col = 'blue')
g_5 <- ggplot(calif_sem, aes(x = sem_5)) + geom_histogram(binwidth = binwidth_min, col = 'red')
g_6 <- ggplot(calif_sem, aes(x = sem_6)) + geom_histogram(binwidth = binwidth_min)
g_1 + g_2 + g_3 + g_4 + g_5 + g_6
``` 



```{r}
ggplot(cal_sem_1, aes(x = estado, y = avg_calif ,fill = estado)) +
  geom_col( ) +
  coord_flip() +
  labs(subtitle = "Promedio semestre uno por estado")
```



```{r}
tabla_estado <- calif_sem %>% 
  group_by( estado, vigencia_clv ) %>%  
  tally()  
```



```{r}
tabla_estado %>%
kable( caption = "vigencia por estado" ) 
```



```{r}
ggplot(tabla_estado, aes(x = estado, y = n,colour = vigencia_clv)) +
  geom_point() +
  coord_flip()
```


```{r}
tabla_estado %>%
  ggplot(aes(x = estado, y = n)) +
  geom_col() +
  coord_flip() +
  facet_wrap(~ vigencia_clv) 
```


```{r}
tabla_sexo <- calif_sem %>% 
  group_by( sexo, vigencia_clv ) %>%  
  tally()  
```

```{r}
tabla_sexo %>%
kable( caption = "vigencia por sexo" ) 
```


```{r}
tabla_sexo %>%
  ggplot(aes(x = sexo, y = n)) +
  geom_col() +
  #geom_point() +
  coord_flip() +
  facet_wrap(~ vigencia_clv) 
```


